import dataclasses
import pathlib
import re
from functools import cached_property, lru_cache
from typing import Literal, NoReturn, Union
from urllib.parse import ParseResult

class BaseModel:
    def __getitem__(self, key) -> Union[int, list, str, dict]: ...
    @cached_property
    def fields(self) -> list[str]: ...
    @cached_property
    def url_object(self) -> ParseResult: ...
    @cached_property
    def get_url_object(self) -> ParseResult: ...
    @cached_property
    def url_stem(self) -> str: ...
    def as_json(self) -> dict: ...
    def as_csv(self) -> list: ...


@dataclasses.dataclass
class Product(BaseModel):
    name: str
    description: str
    price: int
    url: str
    collection_id: str = ...
    number_of_colors: int = Literal[1]
    id_or_reference: str = ...
    id: int = ...
    images: list = ...
    color: str = ...
    composition: str = ...
    color: str = ...
    def __hash__(self) -> int: ...
    @cached_property
    def get_images_url_objects(self) -> list[ParseResult]: ...
    @cached_property
    def number_of_images(self) -> int: ...
    def build_directory_from_url(self, exclude=[]) -> pathlib.Path: ...
    def set_collection_id(self, regex) -> NoReturn: ...
