from functools import cached_property
from typing import Iterator, List, Literal, Union, DefaultDict


def drop_null(items, remove_empty_strings=True) -> Iterator[str, int]: ...


def keep_while(predicate, items) -> Iterator[str, int]: ...


def drop_while(predicate, items) -> Iterator[str, int]: ...


def group_by(predicate, items) -> tuple[List[str, int], List[str, int]]: ...


class CombinedIterators:
    iterators: List[JPEGImagesIterator, EcommercePageImagesIterator] = ...

    def __init__(self, *iterators): ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> str: ...

    def __add__(
        self,
        obj: Union[JPEGImagesIterator, EcommercePageImagesIterator]
    ) -> CombinedIterators: ...

    @cached_property
    def urls(self) -> List[str]: ...

    @cached_property
    def classified_images(self) -> List[List[str]]: ...
    @cached_property
    def as_dict(self) -> dict: ...
    @cached_property
    def as_csv(self) -> List: ...


class PageImagesIterator:
    images_list_filter: list = ...
    urls: list = ...
    page_url: str = ...
    _cached_images: list = ...
    extensions: set = ...

    def __init__(self, current_url: str, image_elements) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[str, int]: ...
    def __len__(self) -> int: ...

    def __add__(
        self,
        obj: Union[JPEGImagesIterator, EcommercePageImagesIterator]
    ) -> CombinedIterators: ...

    @cached_property
    def urls(self) -> List[int]: ...
    @cached_property
    def classified_images(self) -> DefaultDict: ...
    @cached_property
    def as_dict(self) -> dict: ...
    @cached_property
    def as_csv(self) -> list: ...


class JPEGImagesIterator(PageImagesIterator):
    images_list_filter: list = ...


class EcommercePageImagesIterator(JPEGImagesIterator):
    ...


def iterate_chunks(items: Union[list, tuple], n: int) -> List[Iterator]: ...


class AsyncIterator:
    data: Union[list, tuple] = ...
    by: int = ...

    def __init__(self, data: Union[list, tuple], by: int = Literal[10]): ...
    def __alen__(self) -> int: ...
    def __aiter__(self) -> Iterator: ...
