from typing import List, Tuple

from kryptone.contrib.models import Product


class EcommerceCrawlerMixin:
    scroll_step: int = ...
    products: List = ...
    product_objects: List = ...
    seen_products: List = ...
    model: Product = ...

    def seen_products(self, using: str = ...) -> set[str, int]: ...

    def product_exists(
        self,
        product: Product,
        using: str = ...
    ) -> bool: ...

    def add_product(
        self,
        data: dict,
        track_id: bool = ...,
        collection_id_regex: str = ...,
        avoid_duplicates: bool = ...,
        duplicate_key: str = ...
    ) -> Tuple[bool, Product]: ...

    def save_product(
        self,
        data: dict,
        track_id: bool = ...,
        collection_id_regex: str = ...,
        avoid_duplicates: bool = ...,
        duplicate_key: str = ...
    ) -> Tuple[bool, Product]: ...

    def bulk_save_products(
        self,
        data: dict,
        track_id: bool = ...,
        collection_id_regex: str = ...
    ) -> List[Tuple[bool, Product]]: ...

    def save_images(
        self, 
        product: Product, 
        path: str,
        filename: str = ...,
        debug: bool = ...,
        quantity: int = ...
    ) -> None: ...
