from typing import Any, List, Literal, Tuple

from kryptone.contrib.models import Product
from kryptone.utils.urls import URL

TEMPORARY_PRODUCT_CACHE: set[str] = ...


class EcommerceCrawlerMixin:
    scroll_step: int = Literal[30]
    products: List = ...
    product_objects: List = ...
    seen_products: List = ...
    model: Product = ...
    found_products_counter: int = ...
    product_pages: set = ...

    def calculate_performance(self) -> None: ...

    def add_product(
        self,
        data: dict[str, Any],
        collection_id_regex: str = ...,
        avoid_duplicates: bool = ...,
        duplicate_key: str = ...
    ) -> Tuple[bool, Product]: ...

    def save_product(
        self,
        data: dict[str, Any],
        collection_id_regex: str = ...,
        avoid_duplicates: bool = ...,
        duplicate_key: str = ...
    ) -> Tuple[bool, Product]: ...

    def bulk_save_products(
        self,
        data: dict[str, Any],
        track_id: bool = ...,
        collection_id_regex: str = ...
    ) -> List[Product]: ...

    def save_images(
        self,
        product: Product,
        path: str,
        filename: str = ...,
        download_first: bool = ...
    ) -> None: ...

    def capture_product_page(
        self,
        current_url: URL,
        element_class: str = ...,
        element_id: str = ...,
        prefix: str = ...,
        force: bool = ...
    ) -> None: ...
