import dataclasses
import pathlib
from typing import (Any, Callable, Generic, List, Literal,
                    OrderedDict, Type, TypeVar, Union, override)

import pyairtable
import redis
import requests
from requests.models import PreparedRequest

from kryptone.base import SiteCrawler

T = TypeVar('T')

S = TypeVar('S', bound='BaseStorage')

C = TypeVar('C')


def simple_list_adapter(
    data: List[str, int, float]
) -> List[List[str, int, float]]: ...


class BaseStorage(Generic[S, C, T]):
    storage_class: Type[S] = ...
    storage_connection: S = ...
    storage_path: str = ...
    spider: SiteCrawler = ...

    def __init__(self) -> None: ...

    def __get__(
        self,
        cls: Type[SiteCrawler] = ...
    ) -> BaseStorage: ...

    def before_save(self, data: T) -> T: ...
    def initialize(self) -> bool: ...

    async def has(self, key: str) -> bool: ...

    async def get(
        self,
        key: str
    ) -> Union[int, bool, str, dict[str, Any], list[Any]]: ...

    async def save(
        self,
        key: str,
        data: Union[int, bool, str, dict[str, Any], list[Any]],
        adapt_list: bool = ...,
        **kwargs
    ) -> bool: ...

    async def save_or_create(
        self,
        key: str,
        data: Union[int, bool, str, dict[str, Any], list[Any]]
    ) -> bool: ...


@ dataclasses.dataclass
class File:
    path: pathlib.Path

    def __eq__(self, value) -> bool: ...

    @ property
    def is_json(self) -> bool: ...

    @ property
    def is_csv(self) -> bool: ...

    @ property
    def is_image(self) -> bool: ...

    def has(self, key: str) -> bool: ...

    def get(
        self,
        key: str
    ) -> Union[dict, list, bytes]: ...

    def save(
        self,
        key: str,
        data: Union[dict, list, bytes],
        adapt_list: bool = Literal[False],
        **kwargs
    ) -> None: ...


class FileStorage(BaseStorage, Generic[S]):
    storage: OrderedDict[str, File] = ...
    storage_path: Union[str, pathlib.Path] = ...
    csv_adapters: List[Callable[[list[T]], T]]
    ignore_images: bool = ...

    def __init__(self, storage_path: str = ...) -> None: ...

    def __repr__(self) -> str: ...

    @ override
    def initialize(self) -> bool: ...

    @ override
    def has(self, filename: str) -> bool: ...

    @ override
    def get(self, filename: str) -> File: ...

    @ override
    def save(self, filename: str, data: Union[list, dict]) -> bool: ...

    def get_file(self, filename: str) -> File: ...


class RedisStorage(BaseStorage, Generic[S]):
    storage_class: Type[redis.Redis] = ...
    storage_connection: redis.Redis = ...
    is_connected: bool = ...

    def __init__(self) -> None: ...

    @ override
    def initialize(self) -> bool: ...


class AirtableStorage(BaseStorage, Generic[S]):
    storage_class: Type[pyairtable.Api] = ...
    storage_connection: pyairtable.Api = ...

    def __init__(self) -> None: ...


class ApiStorage(BaseStorage, Generic[S]):
    session: requests.Session = ...
    get_endpoint: str = ...
    save_endpoint: str = ...

    def __init__(self) -> None: ...

    @ property
    def default_headers(self) -> dict[str, str]: ...

    def check(self, name: str, data: Any) -> None: ...

    def create_request(
        self, url: str,
        method: Literal['post'] = 'post',
        data: Any = None
    ) -> PreparedRequest: ...

    def get(self, data_name) -> None: ...

    def create(self, data_name, data) -> bool: ...
