from typing import Literal, Union

from requests import Session
from requests.models import Response

class BaseWebhook:
    base_url: str = ...
    current_iteration: int = ...
    session = Session()
    base_pagination: int = ...
    current_slice: list[int, int] = ...
    response: Response = ...
    base_url: str = ...
    auth_token_name: str = ...
    auth_token: str = ...

    def __init__(
        self,
        *,
        url: str = ...,
        auth_token_name: str = Literal['Bearer'],
        auth_token: str = ...
    ): ...
    def __repr__(self) -> str: ...

    def send(self, data: Union[list[dict], dict]) -> None: ...


class Webhook(BaseWebhook):
    ...


class Webhooks:
    webhooks: list[Webhook] = ...
    responses: list[Response] = ...

    def __init__(self, urls: Union[list, tuple]): ...
    def __repr__(self) -> str: ...
    async def resolve(self, data: Union[list[dict], dict]): ...
