from ast import List
from typing import Any, NoReturn, ModuleType


class UserSettings:
    SETTINGS_MODULE: ModuleType = ...
    configured: bool = ...

    def __init__(self, dotted_path: str): ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key) -> Any: ...
    def __setitem__(self, key, value) -> NoReturn: ...


class Settings:
    MODULE: ModuleType = ...
    _user_settings: UserSettings = ...

    def __init__(self) -> NoReturn: ...
    def __repr__(self): ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> NoReturn: ...
    def get(self, name: str) -> Any: ...
    def keys(self) -> List[str]: ...


settings: Settings
